### ISSUE TITLE
Error while trying to create x-ray

### ISSUE THREAD

**Issue by bulu009** [szarroug3/X-Ray_Calibre_Plugin#106]
I am using Calibre 3.33.1 and latest x-ray creator.
This is the output I am getting:

Starting job: Creating Files 

10-22-2018 01:38:27 Initializing... 
10-22-2018 01:38:33 In the Woods - Tana French 
10-22-2018 01:38:33 Parsing Goodreads data... 
Job: "Creating Files" failed with error: 
Traceback (most recent call last):
File "site-packages/calibre/gui2/threaded_jobs.py", line 84, in start_work
File "calibre_plugins.xray_creator.lib.xray_creator ", line 284, in create_files_event
File "calibre_plugins.xray_creator.lib.book", line 223, in create_files_event
File "calibre_plugins.xray_creator.lib.book", line 443, in _parse_goodreads_data
File "calibre_plugins.xray_creator.lib.goodreads_parser ", line 40, in parse
File "calibre_plugins.xray_creator.lib.goodreads_parser ", line 50, in _get_xray
File "calibre_plugins.xray_creator.lib.goodreads_parser ", line 254, in _get_quotes
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u201c' in position 0: ordinal not in range(256)

Called with args: (,) {u'log': , u'abort': , u'notifications': }

**Comment by bulu009** [comment]
Python3 is default.
