### ISSUE TITLE
Cope with bad shelfari data (badly formed glossary entry)

### ISSUE THREAD

**Issue by stoduk** [szarroug3/X-Ray_Calibre_Plugin#35]
While testing the fix for #32 I saw a new issue - for The Lightning Thief there is a glossary entry which has a definition but no term to define.  Obviously this is complete garbage.  In this case the definition was a duplicate of the previous term, so there is no missing data by chance.

No choice but to deal with this, as shelfari data won't/can't be fixed.
```
Before: 
Query: /search/books?Keywords=B00TEFTA80
Shelfari URL search results:
http://www.shelfari.com/books/38590328/Her-Final-Breath
ASIN search: http://www.shelfari.com/books/38590328/Her-Final-Breath
Before: 
Query: /search/books?Keywords=B00280LYIC
Shelfari URL search results:
http://www.shelfari.com/books/73004/The-Lightning-Thief
ASIN search: http://www.shelfari.com/books/73004/The-Lightning-Thief
calibre 2.52  embedded-python: True is64bit: True
Darwin-14.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '14.5.0', 'Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64')
Python 2.7.11
OSX: ('10.10.5', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM && Quality Check && XRay Generator && X-Ray Creator && Goodreads
Traceback (most recent call last):
  File "calibre_plugins.xray_creator.ui", line 93, in book_config
  File "calibre_plugins.xray_creator.book_config", line 45, in __init__
  File "calibre_plugins.xray_creator.lib.book_settings", line 70, in __init__
  File "calibre_plugins.xray_creator.lib.book_settings", line 203, in update_aliases
  File "calibre_plugins.xray_creator.lib.shelfari_parser", line 103, in get_terms
  File "calibre_plugins.xray_creator.lib.shelfari_parser", line 91, in _get_data_from_ul
TypeError: object of type 'NoneType' has no len()
```

**Comment by stoduk** [comment]
Fix works:
```
Job: 1 Creating X-Ray Files finished
Starting job: Creating X-Ray Files 
	 
	05-31-2016 22:57:51 The Lightning Thief - Rick Riordan 
	05-31-2016 22:57:51 	Parsing shelfari data... 
	05-31-2016 22:57:53 	Getting format specific data... 
	05-31-2016 22:57:53 	Parsing book data... 
	05-31-2016 22:57:57 	Creating x-ray... 
	05-31-2016 22:57:57 	Sending x-ray to device... 
	
	X-Ray Creation: 
		Books Completed: 
			The Lightning Thief - Rick Riordan: AZW3 
	
	X-Ray Sending: 
		Books Failed: 
			The Lightning Thief - Rick Riordan: 
				AZW3: No device is connected. 
```
