### ISSUE TITLE
People have been unable to install/update plugin

### ISSUE THREAD

**Issue by szarroug3** [szarroug3/X-Ray_Calibre_Plugin#89]
I was able to recreate the issue by downgrading to 2.2.1 and then trying to update to 3.0.2. Here's the error.

Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 463, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 58, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 199, in load
  File "site-packages\calibre\customize\zipplugin.py", line 183, in load_module
  File "calibre_plugins.xray_creator._ _ init _ _", line 6, in <module>
ImportError: cannot import name _ _ prefs _ _

Note: had to change the double _ to _ _ so github wouldn't markdown the text to bold instead of the actual filename.

**Comment by szarroug3** [comment]
From the investigation I've done so far, it seems like we can't import a global variable in __init__.py. I've added from calibre_plugins.xray_creator.lib.book_parser import PARAGRAPH_PAT before the problem line and the installer seems to break on that line too but has no problem importing BookParser on the same line.
